### ISSUE TITLE
Add automatic tests and enable Github Actions CI

### ISSUE THREAD

**Issue by yungyuc** [r1407p/PyMatrixOpt#1]
There are some google-tests available in the repository and they are good candidates for automatically runs with Github Actions CI.

Python testing will also be useful since the system is supposed to be used in Python.

**Comment by r1407p** [comment]
I have create an Github CI in the branch `build-CI`

**Comment by yungyuc** [comment]
Great, @r1407p .  If it works well, feel free to close this issue.

**Comment by yungyuc** [comment]
Don't forget to capture all the valuable learning in your presentation.

**Comment by r1407p** [comment]
Sure, I will put all the valuable learning in persentation.
